version: '2.2'

services:
  dnsmasq:
    build: .
    image: ismael49/dnsmasq:v2
    cap_add:
      - NET_ADMIN
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf:ro
      - ./hosts:/etc/hosts:ro
      - ./resolv.conf:/etc/resolv.conf:ro
    networks:
      test_net:
        ipv4_address: 192.168.10.10

networks:
  test_net:
    ipam:
      config:
        - subnet: 192.168.10.0/24

